### ISSUE TITLE
Suggestion: Focus follow mouse?

### ISSUE THREAD

**Issue by nipsis** [jcs/sdorfehs#21]
Apologies if this is a silly question...

I have looked around the repo and I couldn't find a sloppy.c file. I have also looked through the man pages and couldn't find anything about it either. Is there any way of replicating the "sloppy" behaviour you find in ratpoison with sdorfehs? It's the only thing that keeps me in ratpoison at the moment...

If this is not part of the sdorfehs vision, is there a way of making sloppy work with sdorfehs?

**Comment by jcs** [comment]
It took me a while to find what you were talking about because I had never heard of that being in Ratpoison, but `sloppy.c` is [only in the `contrib/` directory](https://git.savannah.nongnu.org/cgit/ratpoison.git/tree/contrib/sloppy.c) and the way it's implemented is pretty awful (shelling out to `ratpoison` 3 times and `awk` and `grep` every time the mouse enters a new window).  I'm pretty surprised it's even included in Ratpoison's `contrib/` directory since it kind of goes against the entire spirit of the window manager.  I don't have any intention of adding mouse focusing in sdorfehs.
